name: KakaoCloud-tutorial-server
run-name: kakaoCloud tutorial server workflow
on:
  push:
    paths:
      - 'server/**'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Qemu
      uses: docker/setup-qemu-action@v2

    - name: Login KakaoCloud
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.PROJECT_NAME }}.kr-central-2.kcr.dev
        username: ${{ secrets.ACCESS_KEY }}
        password: ${{ secrets.ACCESS_SECRET_KEY }}

    - uses: actions/checkout@v3

    - name: Build and Push
      uses: docker/build-push-action@v4
      with:
        file: ./server/deploy/Dockerfile
        context: ./server
        push: true
        tags: ${{ secrets.PROJECT_NAME }}.kr-central-2.kcr.dev/${{ secrets.REPOSITORY_NAME }}/kakaocloud-library-server:${{ github.sha }}

  update-deployment-file:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
    - name: Checkout deploy-manifests repository
      uses: actions/checkout@v3
      with:
        repository: ${{ secrets.USERNAME }}/deploy-manifests
        token: ${{ secrets.PAT }}

    - name: Install yq
      run: sudo snap install yq

    - name: Update image in deployment file
      run: |
        yq e '.spec.template.spec.containers[0].image = "${{ secrets.PROJECT_NAME }}.kr-central-2.kcr.dev/${{ secrets.REPOSITORY_NAME }}/kakaocloud-library-server:${{ github.sha }}"' ./deployment-server.yaml -i

    - name: Commit and Push changes
      run: |
        git config --global user.email "${{ secrets.EMAIL }}"
        git config --global user.name "${{ secrets.USERNAME }}"
        git add .
        git commit -m "Update deployment-server.yaml"
        git remote set-url origin https://${{ secrets.PAT }}@github.com/${{ secrets.USERNAME }}/deploy-manifests
        git push --set-upstream origin HEAD
